nameOverride: ""

fullnameOverride: ""

namespaceOverride: ""

global:
  additionalLabels: {}

  imagePullSecrets: []

  deploymentAnnotations: {}

  podAnnotations: {}

  podLabels: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  env: []

deployment:
  image:
    repository: ghcr.io/huggingface/text-generation-inference
    tag: sha-96b7b40
    pullPolicy: IfNotPresent

  model: meta-llama/Meta-Llama-3-8B-Instruct
  
  # 
  # modelOptions:
  #   quantize: bitsandbytes

  resources:
    limits:
      nvidia.com/gpu: 1
    requests:
      cpu: 2
      memory: 5Gi

  tolerations: []

  affinity: {}
