nameOverride: text-generation-inference

fullnameOverride: ""

namespaceOverride: ""

instanceLabelOverride: ""

commonLabels: {}

deployment:
  image:
    repository: ghcr.io/huggingface/text-generation-inference
    tag: sha-96b7b40
    pullPolicy: IfNotPresent

  labels: {}

  podLabels: {}

  annotations: {}

  podAnnotations: {}

  resources:
    limits:
      nvidia.com/gpu: 1
    requests:
      cpu: 2
      memory: 5Gi

  tolerations: []

  affinity: {}

model: meta-llama/Meta-Llama-3-8B-Instruct

modelOptions:
#   quantize: bitsandbytes

modelStorage:
  pvcName: model-storage
  accessModes:
  - ReadWriteOnce
  size: 100Gi

huggingFaceToken:
  secretName: hugging-face-token
  secretKey: token
