apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "llama-cpp.fullname" . }}
  namespace: {{ template "llama-cpp.namespace" .}}
  labels:
    {{- include "llama-cpp.labels" . | nindent 4 }}
    {{- with .Values.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.deployment.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "llama-cpp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "llama-cpp.labels" . | nindent 8 }}
        {{- with .Values.deployment.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.deployment.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: llama-cpp
        image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        command:
        - --all-in-one
        args:
        - -m "/data/"{{ .Values.modelFamily }}/{{ .Values.model }}
        env:
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: shm
          mountPath: /dev/shm
        - name: model-storage
          mountPath: /data
        resources:
          {{- toYaml .Values.deployment.resources | nindent 10 }}
      initContainers:
      - name: download-model
        image: bitnami/git
        command:
        - git
        - clone
        - https://{{ .Values.huggingFaceUser }}:"$(hugging-face-token)"@huggingface.co/{{ .Values.model }}
        - /data/{{ .Values.modelFamily }}
        env:
          - name: hugging-face-token
            valueFrom:
              secretKeyRef:
                name: hugging-face-token
                key: token
      volumes:
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 1Gi
      - name: model-storage
        persistentVolumeClaim:
          claimName: {{ template "llama-cpp.fullname" . }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}


