{{- if $.Values.ingress.enabled -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-oauth-config
type: Opaque
data:
  oauth_client_id: {{ $.Values.oidc.client_id | b64enc }}
  oauth_client_secret: {{ $.Values.oidc.client_secret | b64enc }}
  oauth_cookie_secret: {{ $.Values.oidc.cookie_secret | b64enc }}

{{- end -}}