apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "llama-cpp.fullname" . }}
  namespace: {{ template "llama-cpp.namespace" .}}
  labels:
    app.kubernetes.io/component: llama-cpp
    {{- include "llama-cpp.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: {{ .Values.modelStorage.size }}
  accessModes:
  {{- range .Values.modelStorage.accessModes }}
    - {{ . | quote }}
  {{- end }}
