apiVersion: v1
kind: Service
metadata:
  name: {{ template "llama-cpp.fullname" . }}
  labels:
    app: {{ template "llama-cpp.name" . }}
    chart: {{ template "llama-cpp.chart" . }}
  annotations:
    prometheus.io/scrape: 'true'
spec:
  clusterIP: None
  ports:
  - name: web
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: {{ template "llama-cpp.name" . }}