apiVersion: v1
kind: Service
metadata:
  name: {{ template "llama-cpp.fullname" . }}
  namespace: {{ template "llama-cpp.namespace" .}}
  labels:
    app: {{ template "llama-cpp.name" . }}
    chart: {{ template "llama-cpp.chart" . }}
    app.kubernetes.io/name: {{ template "llama-cpp.name" . }}
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    name: http
  selector:
    app.kubernetes.io/name: {{ template "llama-cpp.name" . }}