apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "chat-ui.fullname" . }}
  namespace: {{ template "chat-ui.namespace" . }}
  labels:
    {{- include "chat-ui.labels" (dict "context" . "component" .Values.chatui.name "name" .Values.chatui.name) | nindent 4 }}
    {{- with (mergeOverwrite (deepCopy .Values.global.deploymentLabels) .Values.chatui.deploymentLabels) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with (mergeOverwrite (deepCopy .Values.global.deploymentAnnotations) .Values.chatui.deploymentAnnotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with (mergeOverwrite (deepCopy .Values.global.deploymentStrategy) .Values.chatui.deploymentStrategy) }}
  strategy:
    {{- trim . | nindent 4 }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  replicas: 1 # TODO Variabilize and even add autoscaling -> https://github.com/argoproj/argo-helm/blob/8c0b68689540eb276ac92d921b2326e706a7ba7f/charts/argo-cd/templates/argocd-server/deployment.yaml#L19
  selector:
    matchLabels:
      {{- include "chat-ui.selectorLabels" (dict "context" . "name" .Values.chatui.name) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chat-ui.labels" (dict "context" . "component" .Values.chatui.name "name" .Values.chatui.name) | nindent 8 }}
        {{- with (mergeOverwrite (deepCopy .Values.global.podLabels) .Values.chatui.podLabels) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with (mergeOverwrite (deepCopy .Values.global.podAnnotations) .Values.chatui.podAnnotations) }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.global.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Values.chatui.name | default "chat-ui" }}
        image: {{ .Values.chatui.image.repository }}:{{ .Values.chatui.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.chatui.image.imagePullPolicy | default .Values.global.imagePullPolicy }}
        env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.huggingFaceToken.secretName }}
              key: {{ .Values.huggingFaceToken.secretKey }}
        {{- if and .Values.mongodb.enabled (not .Values.externalMongodb.host) }}
        - name: MONGODB_URL
          value: {{ printf "mongodb://%s-mongodb:27017" .Release.Name | quote }}
        {{- else if and (not .Values.mongodb.enabled) .Values.externalMongodb.host }}
        - name: MONGODB_URL
          value: {{ printf "mongodb://%s:%d" .Values.externalMongodb.host .Values.externalMongodb.port | quote }}
        {{- else }}
        {{- fail "Either enable embedded MongoDB or provide an external MongoDB host" }}
        {{- end }}
        {{- with .Values.chatui.extraEnv }} # TODO Check if its not better to use a range instead
        {{- toYaml . | nindent 8 }}
        {{- end }}
        readinessProbe:
          failureThreshold: 30
          periodSeconds: 10
          httpGet:
            path: /healthcheck
            port: 3000
        livenessProbe:
          failureThreshold: 30
          periodSeconds: 10
          httpGet:
            path: /healthcheck
            port: 3000
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        # TODO Add conditional to activate metrics
        # - containerPort: 5565
        #   name: metrics
        #   protocol: TCP
        resources:
          {{- toYaml .Values.chatui.resources | nindent 10 }}
      {{- with .Values.chatui.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.chatui.affinity | default .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.chatui.tolerations | default .Values.global.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
