nameOverride: chat-ui

fullnameOverride: ""

namespaceOverride: ""

instanceLabelOverride: ""

commonLabels: {}

deployment:
  image:
    repository: ghcr.io/huggingface/chat-ui
    # tag: sha-d7b02af
    pullPolicy: IfNotPresent

  labels: {}

  podLabels: {}

  annotations: {}

  podAnnotations: {}

  resources: {}

  tolerations: []

  affinity: {}

# TODO
ingress:
  enabled: false
