# TODO Add missing comments
nameOverride: chat-ui

fullnameOverride: ""

namespaceOverride: ""

instanceLabelOverride: ""

global:
  # -- Number of old deployment ReplicaSets to retain. The rest will be garbage collected.
  revisionHistoryLimit: 3

  # -- If defined, a imagePullPolicy applied to all Argo CD deployments.
  imagePullPolicy: IfNotPresent

  # -- Secrets with credentials to pull images from a private registry.
  imagePullSecrets: []

  # -- Common labels for the all resources.
  additionalLabels: {}
    # app: chat-ui

  # -- Labels for the all deployed Deployments.
  deploymentLabels: {}

  # -- Labels for the all deployed pods.
  podLabels: {}

  # -- Annotations for the all deployed Deployments.
  deploymentAnnotations: {}

  # -- Annotations for the all deployed Pods.
  podAnnotations: {}

  # -- Toggle and define pod-level security context.
  # @default -- `{}` (See [values.yaml])
  securityContext: {}
  #  runAsUser: 999
  #  runAsGroup: 999
  #  fsGroup: 999

  # -- Mapping between IP and hostnames that will be injected as entries in the pod's hosts files.
  hostAliases: []
  # - ip: 10.20.30.40
  #   hostnames:
  #   - git.myhostname

  # -- Node selector for all resources. If both nodeSelector and affinity are set, they must both match for the pod to be scheduled onto a node.
  nodeSelector: {}

  # -- Affinity for all resources. If both nodeSelector and affinity are set, they must both match for the pod to be scheduled onto a node.
  affinity: {}

  # -- Tolerations for all resources.
  tolerations: []

  # -- Deployment strategy for the all deployed Deployments.
  deploymentStrategy: {}
    # type: RollingUpdate
    # rollingUpdate:
    #   maxSurge: 25%
    #   maxUnavailable: 25%

chatui:
  name: chat-ui

  image:
    repository: ghcr.io/huggingface/chat-ui
    # tag: sha-d7b02af
    imagePullPolicy: IfNotPresent

  extraEnv: []

  deploymentLabels: {}

  podLabels: {}

  deploymentAnnotations: {}

  podAnnotations: {}

  resources: {}
    # requests:
    #   cpu: 100m
    #   memory: 2Gi
    # limits:
    #   # Recommended to use large limits when web search is enabled
    #   cpu: "4"
    #   memory: 6Gi

  tolerations: []

  nodeSelector: {}

  affinity: {}

  deploymentStrategy: {}

  # TODO
  replicas: 1

  # TODO
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetMemoryUtilizationPercentage: ""
    targetCPUUtilizationPercentage: ""

  # TODO
  metrics:
    enabled: false

  # TODO
  ingress:
    enabled: false

  mongodbUrl:
    secretName: ""
    secretKey: MONGODB_URL

  huggingFaceToken:
    secretName: hugging-face-token
    secretKey: token

# TODO
networkPolicy:
  enabled: false

mongodbSecretInit:
  # -- Enable an init job to create a secret containing credentials to access the MongoDB database. If disabled, the secret must be created another way.
  enabled: true
  
  name: "mongodb-secret-init"

  image:
    repository: ""
    tag: ""
    imagePullPolicy: IfNotPresent

  # -- Override the default command for the init job. If not set, a default command will be used to create the secret.
  commandOverride: []
  # - bash
  # - -c
  # - >-
  #   your command here

  podLabels: {}

  podAnnotations: {}
  
  jobAnnotations: {}

  resources: {}

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  tolerations: []

  nodeSelector: {}

  affinity: {}

# -- Configuration values for the MongoDB Helm chart used as a dependency.
mongodb:
  enabled: true

  # -- Deployment mode for MongoDB. This can be standalone or replicaset. WARNING: replicaset mode is not supported by our chart.
  architecture: standalone
  useStatefulSet: true

  service:
    nameOverride: chat-ui-mongodb

  # auth:
  #   enabled: true
  #   databases: ["chat-ui"] # This must match the database name used in the init job.
  #   usernames: ["chat-ui"] # This must match the username used in the init job.
  #   existingSecret: mongodb-init-secret

  # TODO To test this
  tls:
    enabled: true
    autoGenerated: true
    mTLS:
      enabled: false

  # TODO
  metrics:
    enabled: false
