{{- if and .Values.mongodbSecretInit.enabled (not .Values.externalMongodb.host) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "chat-ui.mongodbSecretInit.fullname" . }}
  namespace: {{ template "chat-ui.namespace" . }}
  labels:
    {{- include "chat-ui.labels" (dict "context" . "component" .Values.mongodbSecretInit.name "name" .Values.mongodbSecretInit.name) | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "chat-ui.mongodbSecretInit.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "chat-ui.mongodbSecretInit.fullname" . }}
{{- end }}
