{{- if and .Values.mongodbSecretInit.enabled (not .Values.chatui.mongodbUrl.secretName) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "chat-ui.mongodbSecretInit.fullname" . }}
  namespace: {{ template "chat-ui.namespace" . }}
  labels:
    {{- include "chat-ui.labels" (dict "context" . "component" .Values.mongodbSecretInit.name "name" .Values.mongodbSecretInit.name) | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - mongodb-init-secret
      - mongodb-url-secret
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
{{- end }}
