{{- if and .Values.mongodbSecretInit.enabled (not .Values.chatui.externalMongodb.host) (not .Values.chatui.mongodbSecretName) }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: {{ template "chat-ui.mongodbSecretInit.fullname" . }}
  namespace: {{ template  "chat-ui.namespace" . }}
  labels:
    {{- include "chat-ui.labels" (dict "context" . "component" .Values.mongodbSecretInit.name "name" .Values.mongodbSecretInit.name) | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
{{- end }}
