apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "text-generation-inference.fullname" . }}
  namespace: {{ template "text-generation-inference.namespace" .}}
  labels:
    app.kubernetes.io/component: text-generation-inference
    {{- include "text-generation-inference.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: {{ .Values.modelStorage.size }}
  accessModes:
  {{- range .Values.modelStorage.accessModes }}
    - {{ . | quote }}
  {{- end }}
