apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "text-generation-inference.fullname" . }}
  namespace: {{ template "text-generation-inference.namespace" .}}
  labels:
    {{- include "text-generation-inference.labels" (dict "context" . "component" .Values.tgi.name "name" .Values.tgi.name) | nindent 4 }}
spec:
  resources:
    requests:
      storage: {{ .Values.tgi.modelStorage.size }}
  accessModes:
  {{- range .Values.tgi.modelStorage.accessModes }}
    - {{ . | quote }}
  {{- end }}
