apiVersion: v1
kind: Service
metadata:
  name: {{ template "text-generation-inference.fullname" . }}
  namespace: {{ template "text-generation-inference.namespace" .}}
  labels:
    {{- include "text-generation-inference.labels" (dict "context" . "component" .Values.tgi.name "name" .Values.tgi.name) | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "text-generation-inference.selectorLabels" (dict "context" . "name" .Values.tgi.name) | nindent 6 }}
  ports:
  - name: api
    port: 8080
    targetPort: 8080
